FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build 
WORKDIR /src
COPY ["isaac.API/isaac.API.csproj/", "isaac.API/"]
RUN dotnet  restore "isaac.API/isaac.API.csproj"
COPY . .
WORKDIR "/src/isaac.API"
RUN dotnet build "isaac.API.csproj" -c Release -o /app/build

FROM build AS publish 
RUN dotnet publish "isaac.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "isaac.API.dll"]
