apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaacapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: isaacapi
  template:
    metadata:
      labels:
        app: isaacapi
    spec:
      containers:
      - name: isaacapi
        image: isaacapi
        ports:
        - containerPort: 80
