apiVersion: apps/v1
kind: Deployment
metadata:
  name: projdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projdev
  template:
    metadata:
      labels:
        app: projdev
    spec:
      containers:
      - name: projdev
        image: projdev:1.0.0.0
        ports:
        - containerPort: 80
